[package]
name = "zerodash-server"
version = "0.0.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15.7"
tracing = "0.1.40"
thiserror = "1.0"
tracing-subscriber = "0.3.18"
surrealdb = "2.0.3"
bytes = "1.7.2"
tower-http = { version = "0.6.1", features = ["normalize-path", "trace"] }
colored = "2.1.0"
